// Расширенные mock данные для должников с полной структурой

export const debtors = [
  {
    id: 1,
    name: 'Иванов Иван Иванович',
    phone: '+7 (495) 123-45-67',
    email: 'ivanov@example.com',
    debt: 45000,
    overdueDays: 45,
    status: 'ready_to_call',
    timezone: 'Europe/Moscow',
    lastCall: '2025-11-01 14:23',
    attempts: 2,
    maxAttempts: 10,
    pipelineId: 'call_debtor_001',
    priority: 'medium',
    address: 'г. Москва',
    
    // Долговые обязательства
    debtObligation: {
      code: 'DO-2024-001234',
      number: '№ 45678/2024',
      type: 'Потребительский кредит',
      conclusionDate: '15.03.2024',
      cessionTransferDate: '20.08.2024',
      issuancePoint: 'Офис №5, г. Москва',
      loanAmount: 50000,
      creditor: 'ООО МФК "Быстрые деньги"',
      overdueDate: '15.09.2024',
      mainInterestRate: 28.5,
      frozen: false,
      organizationName: 'ИП Иванов И.И.',
      workAddress: 'г. Москва, ул. Ленина, д. 10',
      position: 'Менеджер по продажам',
      workPhone: '+7 (495) 111-22-33',
      lendingProgram: 'Экспресс-кредит',
      plannedAmount: 52000,
      documentsCheckDate: '01.10.2024',
      scanCopyState: 'В наличии',
      documentsCompleteness: 'Полный комплект',
      documentsRegistration: 'Оформлены',
      documentsOwnership: 'Оригиналы',
      documentsReadability: 'Хорошая',
      documentsExpiryDate: '31.12.2025',
      documentsRecovery: 'Не требуется',
      borrowerId: 'BR-001234',
      withdrawal: 'Нет',
      withdrawalDate: null,
      executionStage: 'Подготовка',
      executionStatus: 'Не инициировано',
      executionState: 'Новое',
      cessionContract: 'ЦС-2024-5678',
      contractStatus: 'Действующий',
      clientState: 'Активный',
      courtApplicationStatus: 'Не подано',
      courtName: null,
      inProgress: true,
      employeeRecommendation: 'Обзвон в рабочие часы',
      travelDistrict: 'Центральный',
      collectionStage: 'Досудебная',
      executionType: null,
      timezone: 'Europe/Moscow (UTC+3)',
      loanTerm: '12 месяцев',
      extensionPeriod: '12 месяцев',
      extensionCount: 0,
      restructuring: false,
      principalDebt: 45000,
      interest: 3200,
      fines: 1500,
      penalties: 800,
      stateFee: 0,
      legalCosts: 0,
      indexationAmount: 0,
      currency: 'RUB'
    },
    
    // Должник
    debtorInfo: {
      code: 'DBT-001234',
      fullName: 'Иванов Иван Иванович',
      type: 'Физическое лицо',
      birthDate: '12.05.1985',
      passportSeries: '4512',
      passportNumber: '678901',
      passportIssueDate: '20.06.2005',
      passportIssuedBy: 'ОВД Центрального района г. Москвы',
      passportDepartmentCode: '770-045',
      registrationAddress: 'г. Москва, ул. Пушкина, д. 15, кв. 42',
      registrationComment: 'Собственник',
      residenceAddress: 'г. Москва, ул. Пушкина, д. 15, кв. 42',
      residenceComment: 'Проживает по адресу регистрации',
      workPlace: 'ООО "Торговый Дом Центр"',
      birthPlace: 'г. Москва',
      previousSurname: null,
      maritalStatus: 'Женат',
      snils: '123-456-789 01',
      inn: null,
      deathDate: null,
      deathCertificate: null,
      inheritanceCase: null,
      notaryFullName: null,
      notaryChamber: null,
      notaryAddress: null,
      notaryPhone: null
    },
    
    // Контрагенты
    counterparties: [
      {
        code: 'CP-001',
        fullName: 'Иванова Мария Петровна',
        type: 'Поручитель'
      }
    ]
  },
  {
    id: 2,
    name: 'Петрова Мария Сергеевна',
    phone: '+7 (495) 234-56-78',
    email: 'petrova@example.com',
    debt: 78500,
    overdueDays: 60,
    status: 'calling',
    timezone: 'Europe/Moscow',
    lastCall: '2025-11-02 10:15',
    attempts: 1,
    maxAttempts: 10,
    pipelineId: 'call_debtor_002',
    priority: 'high',
    address: 'г. Москва',
    
    debtObligation: {
      code: 'DO-2024-002345',
      number: '№ 56789/2024',
      type: 'Ипотечный кредит',
      conclusionDate: '10.01.2024',
      cessionTransferDate: '15.08.2024',
      issuancePoint: 'Офис №2, г. Москва',
      loanAmount: 85000,
      creditor: 'ПАО "Банк Развитие"',
      overdueDate: '10.09.2024',
      mainInterestRate: 15.0,
      frozen: false,
      organizationName: 'ООО "Красота и здоровье"',
      workAddress: 'г. Москва, пр-т Мира, д. 45',
      position: 'Администратор',
      workPhone: '+7 (495) 222-33-44',
      lendingProgram: 'Ипотека молодым',
      plannedAmount: 95000,
      documentsCheckDate: '25.09.2024',
      scanCopyState: 'В наличии',
      documentsCompleteness: 'Полный комплект',
      documentsRegistration: 'Оформлены',
      documentsOwnership: 'Оригиналы',
      documentsReadability: 'Хорошая',
      documentsExpiryDate: '31.12.2026',
      documentsRecovery: 'Не требуется',
      borrowerId: 'BR-002345',
      withdrawal: 'Нет',
      withdrawalDate: null,
      executionStage: 'Подготовка документов',
      executionStatus: 'В процессе',
      executionState: 'Активное',
      cessionContract: 'ЦС-2024-6789',
      contractStatus: 'Действующий',
      clientState: 'Активный должник',
      courtApplicationStatus: 'Подготовка',
      courtName: 'Тверской районный суд г. Москвы',
      inProgress: true,
      employeeRecommendation: 'Звонить после 18:00',
      travelDistrict: 'Тверской',
      collectionStage: 'Досудебная',
      executionType: 'Взыскание задолженности',
      timezone: 'Europe/Moscow (UTC+3)',
      loanTerm: '180 месяцев',
      extensionPeriod: '180 месяцев',
      extensionCount: 0,
      restructuring: false,
      principalDebt: 78500,
      interest: 5600,
      fines: 2800,
      penalties: 1400,
      stateFee: 0,
      legalCosts: 0,
      indexationAmount: 0,
      currency: 'RUB'
    },
    
    debtorInfo: {
      code: 'DBT-002345',
      fullName: 'Петрова Мария Сергеевна',
      type: 'Физическое лицо',
      birthDate: '25.08.1990',
      passportSeries: '4513',
      passportNumber: '234567',
      passportIssueDate: '15.09.2010',
      passportIssuedBy: 'ОВД Тверского района г. Москвы',
      passportDepartmentCode: '770-032',
      registrationAddress: 'г. Москва, ул. Чехова, д. 28, кв. 15',
      registrationComment: 'Собственник',
      residenceAddress: 'г. Москва, ул. Чехова, д. 28, кв. 15',
      residenceComment: 'Проживает по адресу регистрации',
      workPlace: 'ООО "Красота и здоровье"',
      birthPlace: 'г. Санкт-Петербург',
      previousSurname: 'Смирнова',
      maritalStatus: 'Замужем',
      snils: '234-567-890 12',
      inn: null,
      deathDate: null,
      deathCertificate: null,
      inheritanceCase: null,
      notaryFullName: null,
      notaryChamber: null,
      notaryAddress: null,
      notaryPhone: null
    },
    
    counterparties: [
      {
        code: 'CP-002',
        fullName: 'Петров Сергей Иванович',
        type: 'Созаемщик'
      }
    ]
  },
  {
    id: 3,
    name: 'Сидоров Петр Александрович',
    phone: '+7 (495) 345-67-89',
    email: 'sidorov@example.com',
    debt: 23400,
    overdueDays: 30,
    status: 'success',
    timezone: 'Europe/Moscow',
    lastCall: '2025-11-02 09:45',
    attempts: 3,
    maxAttempts: 10,
    pipelineId: 'call_debtor_003',
    priority: 'low',
    address: 'г. Санкт-Петербург',
    
    debtObligation: {
      code: 'DO-2024-003456',
      number: '№ 67890/2024',
      type: 'Автокредит',
      conclusionDate: '05.06.2024',
      cessionTransferDate: '10.10.2024',
      issuancePoint: 'Офис №8, г. Санкт-Петербург',
      loanAmount: 25000,
      creditor: 'ООО "АвтоФинанс"',
      overdueDate: '05.10.2024',
      mainInterestRate: 18.0,
      frozen: false,
      organizationName: 'ООО "СтройМонтаж"',
      workAddress: 'г. Санкт-Петербург, Невский пр., д. 100',
      position: 'Прораб',
      workPhone: '+7 (812) 111-22-33',
      lendingProgram: 'Автокредит Эконом',
      plannedAmount: 27000,
      documentsCheckDate: '15.10.2024',
      scanCopyState: 'В наличии',
      documentsCompleteness: 'Полный комплект',
      documentsRegistration: 'Оформлены',
      documentsOwnership: 'Оригиналы',
      documentsReadability: 'Отличная',
      documentsExpiryDate: '31.12.2025',
      documentsRecovery: 'Не требуется',
      borrowerId: 'BR-003456',
      withdrawal: 'Нет',
      withdrawalDate: null,
      executionStage: 'Погашено',
      executionStatus: 'Закрыто',
      executionState: 'Завершено',
      cessionContract: 'ЦС-2024-7890',
      contractStatus: 'Исполнен',
      clientState: 'Договорились о погашении',
      courtApplicationStatus: 'Не требуется',
      courtName: null,
      inProgress: false,
      employeeRecommendation: 'Клиент согласился погасить',
      travelDistrict: 'Невский',
      collectionStage: 'Досудебная завершена',
      executionType: null,
      timezone: 'Europe/Moscow (UTC+3)',
      loanTerm: '36 месяцев',
      extensionPeriod: '36 месяцев',
      extensionCount: 0,
      restructuring: false,
      principalDebt: 23400,
      interest: 1200,
      fines: 600,
      penalties: 300,
      stateFee: 0,
      legalCosts: 0,
      indexationAmount: 0,
      currency: 'RUB'
    },
    
    debtorInfo: {
      code: 'DBT-003456',
      fullName: 'Сидоров Петр Александрович',
      type: 'Физическое лицо',
      birthDate: '10.11.1982',
      passportSeries: '4014',
      passportNumber: '345678',
      passportIssueDate: '12.12.2002',
      passportIssuedBy: 'ОВД Невского района г. Санкт-Петербурга',
      passportDepartmentCode: '780-025',
      registrationAddress: 'г. Санкт-Петербург, ул. Ломоносова, д. 5, кв. 78',
      registrationComment: 'Собственник',
      residenceAddress: 'г. Санкт-Петербург, ул. Ломоносова, д. 5, кв. 78',
      residenceComment: 'Проживает по адресу регистрации',
      workPlace: 'ООО "СтройМонтаж"',
      birthPlace: 'г. Санкт-Петербург',
      previousSurname: null,
      maritalStatus: 'Холост',
      snils: '345-678-901 23',
      inn: null,
      deathDate: null,
      deathCertificate: null,
      inheritanceCase: null,
      notaryFullName: null,
      notaryChamber: null,
      notaryAddress: null,
      notaryPhone: null
    },
    
    counterparties: []
  },
  {
    id: 4,
    name: 'Козлова Анна Викторовна',
    phone: '+7 (495) 456-78-90',
    email: 'kozlova@example.com',
    debt: 156000,
    overdueDays: 120,
    status: 'fail_busy',
    timezone: 'Europe/Moscow',
    lastCall: '2025-11-02 11:30',
    attempts: 4,
    maxAttempts: 10,
    pipelineId: 'call_debtor_004',
    priority: 'high',
    address: 'г. Москва',
    
    debtObligation: {
      code: 'DO-2024-004567',
      number: '№ 78901/2024',
      type: 'Бизнес-кредит',
      conclusionDate: '20.02.2024',
      cessionTransferDate: '01.07.2024',
      issuancePoint: 'Офис №1, г. Москва',
      loanAmount: 180000,
      creditor: 'АО "БизнесБанк"',
      overdueDate: '20.07.2024',
      mainInterestRate: 22.0,
      frozen: false,
      organizationName: 'ИП Козлова А.В.',
      workAddress: 'г. Москва, ул. Арбат, д. 12',
      position: 'Индивидуальный предприниматель',
      workPhone: '+7 (495) 333-44-55',
      lendingProgram: 'Бизнес-старт',
      plannedAmount: 175000,
      documentsCheckDate: '10.08.2024',
      scanCopyState: 'В наличии',
      documentsCompleteness: 'Полный комплект',
      documentsRegistration: 'Оформлены',
      documentsOwnership: 'Оригиналы',
      documentsReadability: 'Хорошая',
      documentsExpiryDate: '31.12.2025',
      documentsRecovery: 'Не требуется',
      borrowerId: 'BR-004567',
      withdrawal: 'Нет',
      withdrawalDate: null,
      executionStage: 'Судебное разбирательство',
      executionStatus: 'В суде',
      executionState: 'Активное',
      cessionContract: 'ЦС-2024-8901',
      contractStatus: 'Действующий',
      clientState: 'Не выходит на связь',
      courtApplicationStatus: 'Подано',
      courtName: 'Арбатский районный суд г. Москвы',
      inProgress: true,
      employeeRecommendation: 'Попытки в разное время',
      travelDistrict: 'Арбатский',
      collectionStage: 'Судебная',
      executionType: 'Взыскание задолженности',
      timezone: 'Europe/Moscow (UTC+3)',
      loanTerm: '24 месяца',
      extensionPeriod: '24 месяца',
      extensionCount: 0,
      restructuring: false,
      principalDebt: 156000,
      interest: 12000,
      fines: 8000,
      penalties: 4500,
      stateFee: 3200,
      legalCosts: 5000,
      indexationAmount: 2300,
      currency: 'RUB'
    },
    
    debtorInfo: {
      code: 'DBT-004567',
      fullName: 'Козлова Анна Викторовна',
      type: 'Индивидуальный предприниматель',
      birthDate: '03.04.1988',
      passportSeries: '4515',
      passportNumber: '456789',
      passportIssueDate: '05.05.2008',
      passportIssuedBy: 'ОВД Арбатского района г. Москвы',
      passportDepartmentCode: '770-018',
      registrationAddress: 'г. Москва, ул. Новый Арбат, д. 24, кв. 88',
      registrationComment: 'Собственник',
      residenceAddress: 'г. Москва, ул. Новый Арбат, д. 24, кв. 88',
      residenceComment: 'Проживает по адресу регистрации',
      workPlace: 'ИП Козлова А.В.',
      birthPlace: 'г. Москва',
      previousSurname: 'Федорова',
      maritalStatus: 'Разведена',
      snils: '456-789-012 34',
      inn: '773012345678',
      deathDate: null,
      deathCertificate: null,
      inheritanceCase: null,
      notaryFullName: null,
      notaryChamber: null,
      notaryAddress: null,
      notaryPhone: null
    },
    
    counterparties: []
  },
  {
    id: 5,
    name: 'Морозов Дмитрий Олегович',
    phone: '+7 (495) 567-89-01',
    email: 'morozov@example.com',
    debt: 92300,
    overdueDays: 75,
    status: 'time_check',
    timezone: 'Asia/Vladivostok',
    lastCall: '2025-11-01 16:20',
    attempts: 1,
    maxAttempts: 10,
    pipelineId: 'call_debtor_005',
    priority: 'high',
    address: 'г. Владивосток',
    
    debtObligation: {
      code: 'DO-2024-005678',
      number: '№ 89012/2024',
      type: 'Потребительский кредит',
      conclusionDate: '12.04.2024',
      cessionTransferDate: '18.08.2024',
      issuancePoint: 'Офис №15, г. Владивосток',
      loanAmount: 100000,
      creditor: 'ООО МФК "Восток"',
      overdueDate: '12.08.2024',
      mainInterestRate: 32.0,
      frozen: false,
      organizationName: 'ООО "Морские перевозки"',
      workAddress: 'г. Владивосток, ул. Портовая, д. 7',
      position: 'Логист',
      workPhone: '+7 (423) 111-22-33',
      lendingProgram: 'Срочный займ',
      plannedAmount: 105000,
      documentsCheckDate: '25.08.2024',
      scanCopyState: 'В наличии',
      documentsCompleteness: 'Полный комплект',
      documentsRegistration: 'Оформлены',
      documentsOwnership: 'Оригиналы',
      documentsReadability: 'Хорошая',
      documentsExpiryDate: '31.12.2025',
      documentsRecovery: 'Не требуется',
      borrowerId: 'BR-005678',
      withdrawal: 'Нет',
      withdrawalDate: null,
      executionStage: 'Подготовка',
      executionStatus: 'Проверка времени',
      executionState: 'Ожидание',
      cessionContract: 'ЦС-2024-9012',
      contractStatus: 'Действующий',
      clientState: 'Ожидание звонка',
      courtApplicationStatus: 'Не подано',
      courtName: null,
      inProgress: true,
      employeeRecommendation: 'Учитывать разницу во времени +7 часов',
      travelDistrict: 'Приморский',
      collectionStage: 'Досудебная',
      executionType: null,
      timezone: 'Asia/Vladivostok (UTC+10)',
      loanTerm: '18 месяцев',
      extensionPeriod: '18 месяцев',
      extensionCount: 0,
      restructuring: false,
      principalDebt: 92300,
      interest: 7800,
      fines: 3200,
      penalties: 1500,
      stateFee: 0,
      legalCosts: 0,
      indexationAmount: 0,
      currency: 'RUB'
    },
    
    debtorInfo: {
      code: 'DBT-005678',
      fullName: 'Морозов Дмитрий Олегович',
      type: 'Физическое лицо',
      birthDate: '22.07.1991',
      passportSeries: '2516',
      passportNumber: '567890',
      passportIssueDate: '30.08.2011',
      passportIssuedBy: 'ОВД Первореченского района г. Владивостока',
      passportDepartmentCode: '250-012',
      registrationAddress: 'г. Владивосток, ул. Светланская, д. 45, кв. 12',
      registrationComment: 'Собственник',
      residenceAddress: 'г. Владивосток, ул. Светланская, д. 45, кв. 12',
      residenceComment: 'Проживает по адресу регистрации',
      workPlace: 'ООО "Морские перевозки"',
      birthPlace: 'г. Владивосток',
      previousSurname: null,
      maritalStatus: 'Женат',
      snils: '567-890-123 45',
      inn: null,
      deathDate: null,
      deathCertificate: null,
      inheritanceCase: null,
      notaryFullName: null,
      notaryChamber: null,
      notaryAddress: null,
      notaryPhone: null
    },
    
    counterparties: [
      {
        code: 'CP-005',
        fullName: 'Морозова Елена Сергеевна',
        type: 'Супруга'
      }
    ]
  },
  {
    id: 6,
    name: 'Васильева Елена Игоревна',
    phone: '+7 (495) 678-90-12',
    email: 'vasileva@example.com',
    debt: 34700,
    overdueDays: 15,
    status: 'new',
    timezone: 'Europe/Moscow',
    lastCall: null,
    attempts: 0,
    maxAttempts: 10,
    pipelineId: 'call_debtor_006',
    priority: 'medium',
    address: 'г. Казань',
    
    debtObligation: {
      code: 'DO-2024-006789',
      number: '№ 90123/2024',
      type: 'Микрозайм',
      conclusionDate: '18.10.2024',
      cessionTransferDate: '25.10.2024',
      issuancePoint: 'Офис №20, г. Казань',
      loanAmount: 35000,
      creditor: 'ООО МКК "Деньги сразу"',
      overdueDate: '18.10.2024',
      mainInterestRate: 45.0,
      frozen: false,
      organizationName: 'ООО "Текстиль+"',
      workAddress: 'г. Казань, ул. Баумана, д. 33',
      position: 'Швея',
      workPhone: '+7 (843) 111-22-33',
      lendingProgram: 'Микрозайм до зарплаты',
      plannedAmount: 38000,
      documentsCheckDate: '01.11.2024',
      scanCopyState: 'Ожидается',
      documentsCompleteness: 'Частичный',
      documentsRegistration: 'В процессе',
      documentsOwnership: 'Копии',
      documentsReadability: 'Удовлетворительная',
      documentsExpiryDate: '31.12.2025',
      documentsRecovery: 'Не требуется',
      borrowerId: 'BR-006789',
      withdrawal: 'Нет',
      withdrawalDate: null,
      executionStage: 'Новое',
      executionStatus: 'Не начато',
      executionState: 'Новое',
      cessionContract: 'ЦС-2024-0123',
      contractStatus: 'Действующий',
      clientState: 'Новый клиент',
      courtApplicationStatus: 'Не подано',
      courtName: null,
      inProgress: false,
      employeeRecommendation: 'Первичный контакт',
      travelDistrict: 'Вахитовский',
      collectionStage: 'Досудебная',
      executionType: null,
      timezone: 'Europe/Moscow (UTC+3)',
      loanTerm: '3 месяца',
      extensionPeriod: '3 месяца',
      extensionCount: 0,
      restructuring: false,
      principalDebt: 34700,
      interest: 1800,
      fines: 500,
      penalties: 200,
      stateFee: 0,
      legalCosts: 0,
      indexationAmount: 0,
      currency: 'RUB'
    },
    
    debtorInfo: {
      code: 'DBT-006789',
      fullName: 'Васильева Елена Игоревна',
      type: 'Физическое лицо',
      birthDate: '15.09.1995',
      passportSeries: '9217',
      passportNumber: '678901',
      passportIssueDate: '20.10.2015',
      passportIssuedBy: 'ОВД Вахитовского района г. Казани',
      passportDepartmentCode: '920-008',
      registrationAddress: 'г. Казань, ул. Пушкина, д. 78, кв. 45',
      registrationComment: 'Съемное жилье',
      residenceAddress: 'г. Казань, ул. Пушкина, д. 78, кв. 45',
      residenceComment: 'Проживает по адресу регистрации',
      workPlace: 'ООО "Текстиль+"',
      birthPlace: 'г. Казань',
      previousSurname: null,
      maritalStatus: 'Не замужем',
      snils: '678-901-234 56',
      inn: null,
      deathDate: null,
      deathCertificate: null,
      inheritanceCase: null,
      notaryFullName: null,
      notaryChamber: null,
      notaryAddress: null,
      notaryPhone: null
    },
    
    counterparties: []
  },
  {
    id: 7,
    name: 'Смирнов Алексей Павлович',
    phone: '+7 (495) 789-01-23',
    email: 'smirnov@example.com',
    debt: 67800,
    overdueDays: 90,
    status: 'fail_no_answer',
    timezone: 'Europe/Moscow',
    lastCall: '2025-11-02 13:10',
    attempts: 5,
    maxAttempts: 10,
    pipelineId: 'call_debtor_007',
    priority: 'medium',
    address: 'г. Екатеринбург',
    
    debtObligation: {
      code: 'DO-2024-007890',
      number: '№ 01234/2024',
      type: 'Потребительский кредит',
      conclusionDate: '28.05.2024',
      cessionTransferDate: '05.08.2024',
      issuancePoint: 'Офис №12, г. Екатеринбург',
      loanAmount: 70000,
      creditor: 'ПАО "УралБанк"',
      overdueDate: '28.08.2024',
      mainInterestRate: 25.0,
      frozen: false,
      organizationName: 'ИП Смирнов А.П.',
      workAddress: 'г. Екатеринбург, ул. Ленина, д. 52',
      position: 'Индивидуальный предприниматель',
      workPhone: '+7 (343) 111-22-33',
      lendingProgram: 'Кре��ит наличными',
      plannedAmount: 75000,
      documentsCheckDate: '15.09.2024',
      scanCopyState: 'В наличии',
      documentsCompleteness: 'Полный комплект',
      documentsRegistration: 'Оформлены',
      documentsOwnership: 'Оригиналы',
      documentsReadability: 'Хорошая',
      documentsExpiryDate: '31.12.2025',
      documentsRecovery: 'Не требуется',
      borrowerId: 'BR-007890',
      withdrawal: 'Нет',
      withdrawalDate: null,
      executionStage: 'Активный поиск',
      executionStatus: 'Не отвечает',
      executionState: 'Проблемное',
      cessionContract: 'ЦС-2024-1234',
      contractStatus: 'Действующий',
      clientState: 'Не выходит на связь',
      courtApplicationStatus: 'Рассматривается',
      courtName: 'Ленинский районный суд г. Екатеринбурга',
      inProgress: true,
      employeeRecommendation: 'SMS уведомления, звонки в разное время',
      travelDistrict: 'Ленинский',
      collectionStage: 'Досудебная (углубленная)',
      executionType: 'Взыскание задолженности',
      timezone: 'Asia/Yekaterinburg (UTC+5)',
      loanTerm: '24 месяца',
      extensionPeriod: '24 месяца',
      extensionCount: 0,
      restructuring: false,
      principalDebt: 67800,
      interest: 5200,
      fines: 2500,
      penalties: 1200,
      stateFee: 0,
      legalCosts: 0,
      indexationAmount: 0,
      currency: 'RUB'
    },
    
    debtorInfo: {
      code: 'DBT-007890',
      fullName: 'Смирнов Алексей Павлович',
      type: 'Индивидуальный предприниматель',
      birthDate: '08.03.1987',
      passportSeries: '6518',
      passportNumber: '789012',
      passportIssueDate: '12.04.2007',
      passportIssuedBy: 'ОВД Ленинского района г. Екатеринбурга',
      passportDepartmentCode: '660-015',
      registrationAddress: 'г. Екатеринбург, ул. Малышева, д. 101, кв. 67',
      registrationComment: 'Собственник',
      residenceAddress: 'г. Екатеринбург, ул. Малышева, д. 101, кв. 67',
      residenceComment: 'Проживает по адресу регистрации',
      workPlace: 'ИП Смирнов А.П.',
      birthPlace: 'г. Екатеринбург',
      previousSurname: null,
      maritalStatus: 'Холост',
      snils: '789-012-345 67',
      inn: '660123456789',
      deathDate: null,
      deathCertificate: null,
      inheritanceCase: null,
      notaryFullName: null,
      notaryChamber: null,
      notaryAddress: null,
      notaryPhone: null
    },
    
    counterparties: []
  },
  {
    id: 8,
    name: 'Новикова Ольга Андреевна',
    phone: '+7 (495) 890-12-34',
    email: 'novikova@example.com',
    debt: 123500,
    overdueDays: 105,
    status: 'ready_to_call',
    timezone: 'Europe/Moscow',
    lastCall: '2025-11-01 15:45',
    attempts: 2,
    maxAttempts: 10,
    pipelineId: 'call_debtor_008',
    priority: 'high',
    address: 'г. Москва',
    
    debtObligation: {
      code: 'DO-2024-008901',
      number: '№ 12345/2024',
      type: 'Ипотечный кредит',
      conclusionDate: '15.04.2024',
      cessionTransferDate: '20.07.2024',
      issuancePoint: 'Офис №3, г. Москва',
      loanAmount: 150000,
      creditor: 'ПАО "МосБанк"',
      overdueDate: '15.07.2024',
      mainInterestRate: 12.5,
      frozen: false,
      organizationName: 'ООО "ФармаЛайф"',
      workAddress: 'г. Москва, Кутузовский пр., д. 21',
      position: 'Менеджер',
      workPhone: '+7 (495) 444-55-66',
      lendingProgram: 'Семейная ипотека',
      plannedAmount: 165000,
      documentsCheckDate: '30.08.2024',
      scanCopyState: 'В наличии',
      documentsCompleteness: 'Полный комплект',
      documentsRegistration: 'Оформлены',
      documentsOwnership: 'Оригиналы',
      documentsReadability: 'Отличная',
      documentsExpiryDate: '31.12.2026',
      documentsRecovery: 'Не требуется',
      borrowerId: 'BR-008901',
      withdrawal: 'Нет',
      withdrawalDate: null,
      executionStage: 'Переговоры',
      executionStatus: 'Активный контакт',
      executionState: 'Активное',
      cessionContract: 'ЦС-2024-2345',
      contractStatus: 'Действующий',
      clientState: 'На связи',
      courtApplicationStatus: 'Приостановлено',
      courtName: 'Дорогомиловский районный суд г. Москвы',
      inProgress: true,
      employeeRecommendation: 'Клиент готов обсуждать варианты',
      travelDistrict: 'Дорогомиловский',
      collectionStage: 'Досудебная',
      executionType: null,
      timezone: 'Europe/Moscow (UTC+3)',
      loanTerm: '240 месяцев',
      extensionPeriod: '240 месяцев',
      extensionCount: 0,
      restructuring: true,
      principalDebt: 123500,
      interest: 9800,
      fines: 5200,
      penalties: 2800,
      stateFee: 0,
      legalCosts: 0,
      indexationAmount: 0,
      currency: 'RUB'
    },
    
    debtorInfo: {
      code: 'DBT-008901',
      fullName: 'Новикова Ольга Андреевна',
      type: 'Физическое лицо',
      birthDate: '29.11.1989',
      passportSeries: '4519',
      passportNumber: '890123',
      passportIssueDate: '15.12.2009',
      passportIssuedBy: 'ОВД Дорогомиловского района г. Москвы',
      passportDepartmentCode: '770-028',
      registrationAddress: 'г. Москва, Кутузовский пр., д. 15, кв. 120',
      registrationComment: 'Собственник',
      residenceAddress: 'г. Москва, Кутузовский пр., д. 15, кв. 120',
      residenceComment: 'Проживает по адресу регистрации',
      workPlace: 'ООО "ФармаЛайф"',
      birthPlace: 'г. Москва',
      previousSurname: null,
      maritalStatus: 'Замужем',
      snils: '890-123-456 78',
      inn: null,
      deathDate: null,
      deathCertificate: null,
      inheritanceCase: null,
      notaryFullName: null,
      notaryChamber: null,
      notaryAddress: null,
      notaryPhone: null
    },
    
    counterparties: [
      {
        code: 'CP-008',
        fullName: 'Новиков Андрей Владимирович',
        type: 'Созаемщик'
      }
    ]
  }
];
